//! Conversion from JSON Schema (draft 2020-12, as generated by schemars) to
//! TD `DataSchema`.
//!
//! TD `DataSchema` is close to JSON Schema but not the same.
//!
//! 1. **`$ref` is inlined**, because a TD can't refer to other schemas.
//!    Only local references (`#…`) are resolved. Keywords next to a `$ref`
//!    (such as a field's `description` or `default`) override the referenced
//!    schema's. Each reference followed, and each level
//!    of nesting, counts towards a recursion limit (99), so a
//!    recursive type fails instead of expanding forever.
//! 2. **`anyOf` becomes `oneOf`**, the only union TD has. Having both is an error.
//! 3. **`prefixItems` becomes `items`** (an array: the TD form of a tuple).
//!    An `items: false` next to it is dropped, because `maxItems` already
//!    closes the tuple. Any other `items` next to it is an error.
//! 4. **A `type` array becomes `oneOf`**: TD `type` must be a single
//!    string. Keywords that only apply to one type (`minimum`, `items`,
//!    `properties`, …) move into that type's branch, and `enum`/`const`
//!    values go to the branch of their own type. Redundant types are removed;
//!    `number` includes `integer`.
//! 5. **`$defs`, `definitions`, `$schema` and `$id` are removed.**
//! 6. **Non-standard numeric `format`s** that schemars adds (`int32`,
//!    `uint8`, `double`, …) are removed. The bounds schemars adds for
//!    unsigned and small integers (`minimum: 0`, `maximum: 255`) stay.
//! 7. **A `null` `default` is removed**, and `const: null` becomes `type: "null"`
//!    when compatible with the declared type. Contradictory types are rejected.
//! 8. **A single-element `allOf` is merged** into the schema around it.
//! 9. Schema **booleans**: `true` becomes `{}` wherever TD expects a
//!    DataSchema, and `false` is an error there. Booleans are kept where TD
//!    doesn't define the keyword (for example `additionalProperties: false`).
//! 10. **Keywords are sorted alphabetically** in every converted schema, as
//!     pydantic sorts the JSON Schema it generates. Typed [`DataSchema`] terms
//!     are written in the model's order anyway, so this only affects terms TD
//!     doesn't define (such as a nested `additionalProperties` schema). Member
//!     names inside `properties` keep their order.
//!
//! Only keywords that hold schemas are converted. Values inside `default`,
//! `const`, `enum` and `examples` are left alone.

use schemars::JsonSchema;
use schemars::generate::SchemaSettings;
use serde_json::{Map, Value};

use crate::DataSchema;

/// Recursion limit for schema conversion.
pub const DEFAULT_RECURSION_LIMIT: usize = 99;

/// Options for the conversion.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ConversionOptions {
    /// How many levels of nesting, plus references followed, are allowed
    /// before the conversion gives up.
    pub recursion_limit: usize,
}

impl Default for ConversionOptions {
    fn default() -> Self {
        Self {
            recursion_limit: DEFAULT_RECURSION_LIMIT,
        }
    }
}

/// A JSON Schema can't be converted to a TD `DataSchema`.
///
/// `path` is where the problem is in the *converted* schema, as a JSON
/// pointer fragment such as `#/properties/position`.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum ConversionError {
    /// Nesting plus references exceeded the recursion limit.
    #[error("recursion limit of {limit} exceeded at {path}: is the type recursive?")]
    RecursionLimit {
        /// The limit.
        limit: usize,
        /// Where it was exceeded.
        path: String,
    },
    /// A `$ref` points outside the schema document.
    #[error(
        "only local references (starting with `#`) can be resolved, not `{reference}` (at {path})"
    )]
    NonLocalReference {
        /// The reference.
        reference: String,
        /// Where it is.
        path: String,
    },
    /// A `$ref` points to nothing.
    #[error("reference `{reference}` was not found in the schema (at {path})")]
    UnresolvedReference {
        /// The reference.
        reference: String,
        /// Where it is.
        path: String,
    },
    /// A keyword that can't be converted.
    #[error("`{keyword}` is not supported (at {path})")]
    Unsupported {
        /// The keyword.
        keyword: String,
        /// Where it is.
        path: String,
    },
    /// Keywords that contradict each other or can't be combined.
    #[error("{message} (at {path})")]
    Conflict {
        /// What is wrong.
        message: String,
        /// Where it is.
        path: String,
    },
    /// The schema `false` (no valid value) where TD needs a DataSchema.
    #[error("the schema `false` can't be expressed as a DataSchema (at {path})")]
    FalseSchema {
        /// Where it is.
        path: String,
    },
    /// Something that isn't a schema where a schema was expected.
    #[error("expected a schema (an object or a boolean), found `{found}` (at {path})")]
    NotASchema {
        /// The value found.
        found: String,
        /// Where it is.
        path: String,
    },
    /// The converted schema doesn't fit the TD `DataSchema` model, for
    /// example because `type` names an unknown type.
    #[error("the converted schema is not a valid DataSchema: {source}\n{schema}")]
    InvalidDataSchema {
        /// The error from deserialising the converted schema.
        source: serde_json::Error,
        /// The converted schema, pretty-printed.
        schema: String,
    },
}

impl DataSchema {
    /// The DataSchema of a Rust type, derived with schemars and converted.
    ///
    /// schemars titles a root schema with the type's schema name (such as
    /// `Nullable_int64`); that generated title is removed, so titles only
    /// come from `#[schemars(title = …)]`. Descriptions come from doc
    /// comments.
    ///
    /// ```
    /// # use teta_wot_td::{DataSchema, DataType};
    /// let schema = DataSchema::for_type::<Option<u8>>().unwrap();
    /// let branches = schema.one_of.unwrap();
    /// assert_eq!(branches[0].data_type, Some(DataType::Integer));
    /// assert_eq!(branches[0].maximum, Some(255.into()));
    /// assert_eq!(branches[1].data_type, Some(DataType::Null));
    /// ```
    pub fn for_type<T: JsonSchema>() -> Result<Self, ConversionError> {
        let mut schema = SchemaSettings::draft2020_12()
            .into_generator()
            .into_root_schema_for::<T>()
            .to_value();
        if let Value::Object(map) = &mut schema
            && map.get("title").and_then(Value::as_str) == Some(T::schema_name().as_ref())
        {
            map.shift_remove("title");
        }
        from_json_schema(&schema)
    }
}

/// Converts a JSON Schema document to a TD `DataSchema`.
pub fn from_json_schema(schema: &Value) -> Result<DataSchema, ConversionError> {
    from_json_schema_with(schema, &ConversionOptions::default())
}

/// Converts a JSON Schema document to a TD `DataSchema`, with options.
pub fn from_json_schema_with(
    schema: &Value,
    options: &ConversionOptions,
) -> Result<DataSchema, ConversionError> {
    let converted = convert(schema, options)?;
    serde_json::from_value(converted.clone()).map_err(|source| ConversionError::InvalidDataSchema {
        source,
        schema: serde_json::to_string_pretty(&converted).unwrap_or_default(),
    })
}

/// Converts a JSON Schema document to DataSchema JSON, without checking it
/// against the [`DataSchema`] model. Useful for seeing what the conversion does.
pub fn convert(schema: &Value, options: &ConversionOptions) -> Result<Value, ConversionError> {
    let converter = Converter {
        root: schema,
        limit: options.recursion_limit,
    };
    converter.data_schema(schema, 0, "#").map(Value::Object)
}

struct Converter<'a> {
    root: &'a Value,
    limit: usize,
}

impl Converter<'_> {
    /// Converts a schema in a position where TD expects a DataSchema.
    fn data_schema(
        &self,
        schema: &Value,
        mut depth: usize,
        path: &str,
    ) -> Result<Map<String, Value>, ConversionError> {
        self.check_depth(depth, path)?;
        let mut obj = as_schema_object(schema.clone(), path)?;

        // References and single-element `allOf`s, until neither is left.
        loop {
            if let Some(reference) = obj.shift_remove("$ref") {
                let target = self.resolve(&reference, path)?;
                depth += 1;
                self.check_depth(depth, path)?;
                obj = merge(as_schema_object(target.clone(), path)?, obj);
            } else if let Some(Value::Array(all_of)) = obj.get("allOf")
                && all_of.len() == 1
            {
                let Some(Value::Array(mut all_of)) = obj.shift_remove("allOf") else {
                    unreachable!("checked above")
                };
                let element = all_of.pop().expect("checked above");
                depth += 1;
                self.check_depth(depth, path)?;
                obj = merge(as_schema_object(element, path)?, obj);
            } else {
                break;
            }
        }

        for keyword in ["$schema", "$id", "$defs", "definitions"] {
            obj.shift_remove(keyword);
        }
        for keyword in ["$dynamicRef", "$recursiveRef"] {
            if obj.contains_key(keyword) {
                return Err(ConversionError::Unsupported {
                    keyword: keyword.to_owned(),
                    path: path.to_owned(),
                });
            }
        }

        if let Some(any_of) = obj.shift_remove("anyOf") {
            if obj.contains_key("oneOf") {
                return Err(conflict("both `anyOf` and `oneOf` are present", path));
            }
            obj.insert("oneOf".to_owned(), any_of);
        }

        if obj.get("default") == Some(&Value::Null) {
            obj.shift_remove("default");
        }
        if let Some(prefix_items) = obj.shift_remove("prefixItems") {
            match obj.shift_remove("items") {
                None | Some(Value::Bool(false)) => {}
                Some(_) => {
                    return Err(conflict("both `prefixItems` and `items` are present", path));
                }
            }
            obj.insert("items".to_owned(), prefix_items);
        }

        if let Some(Value::Array(types)) = obj.get("type") {
            let types = types.clone();
            split_type_array(&mut obj, &types, path)?;
        }

        if obj.get("const") == Some(&Value::Null) {
            let compatible = match obj.get("type") {
                None => true,
                Some(Value::String(data_type)) => data_type == "null",
                _ => false,
            };
            if !compatible {
                return Err(conflict("`const: null` conflicts with `type`", path));
            }
            obj.shift_remove("const");
            obj.entry("type").or_insert_with(|| "null".into());
        }

        if matches!(
            obj.get("type").and_then(Value::as_str),
            Some("integer" | "number")
        ) && obj
            .get("format")
            .and_then(Value::as_str)
            .is_some_and(is_numeric_format)
        {
            obj.shift_remove("format");
        }

        self.children(&mut obj, depth + 1, path)?;
        obj.sort_keys();
        Ok(obj)
    }

    /// Converts the schemas nested inside `obj`.
    fn children(
        &self,
        obj: &mut Map<String, Value>,
        depth: usize,
        path: &str,
    ) -> Result<(), ConversionError> {
        // Keywords whose value is a map of DataSchemas.
        if let Some(Value::Object(properties)) = obj.get_mut("properties") {
            for (name, schema) in properties.iter_mut() {
                let child = format!("{path}/properties/{}", escape(name));
                *schema = Value::Object(self.data_schema(schema, depth, &child)?);
            }
        }
        // `items`: one DataSchema, or an array of them.
        match obj.get_mut("items") {
            Some(Value::Array(items)) => {
                for (i, schema) in items.iter_mut().enumerate() {
                    let child = format!("{path}/items/{i}");
                    *schema = Value::Object(self.data_schema(schema, depth, &child)?);
                }
            }
            Some(schema) => {
                let child = format!("{path}/items");
                *schema = Value::Object(self.data_schema(schema, depth, &child)?);
            }
            None => {}
        }
        // `oneOf`: an array of DataSchemas.
        if let Some(Value::Array(one_of)) = obj.get_mut("oneOf") {
            for (i, schema) in one_of.iter_mut().enumerate() {
                let child = format!("{path}/oneOf/{i}");
                *schema = Value::Object(self.data_schema(schema, depth, &child)?);
            }
        }
        // JSON Schema keywords that TD doesn't define: convert schemas, keep booleans.
        for keyword in [
            "additionalProperties",
            "unevaluatedProperties",
            "additionalItems",
            "unevaluatedItems",
            "propertyNames",
            "contains",
            "not",
            "if",
            "then",
            "else",
            "contentSchema",
        ] {
            if let Some(schema) = obj.get_mut(keyword) {
                let child = format!("{path}/{keyword}");
                *schema = self.extension_schema(schema, depth, &child)?;
            }
        }
        for keyword in ["patternProperties", "dependentSchemas"] {
            if let Some(Value::Object(schemas)) = obj.get_mut(keyword) {
                for (name, schema) in schemas.iter_mut() {
                    let child = format!("{path}/{keyword}/{}", escape(name));
                    *schema = self.extension_schema(schema, depth, &child)?;
                }
            }
        }
        if let Some(Value::Array(all_of)) = obj.get_mut("allOf") {
            for (i, schema) in all_of.iter_mut().enumerate() {
                let child = format!("{path}/allOf/{i}");
                *schema = self.extension_schema(schema, depth, &child)?;
            }
        }
        Ok(())
    }

    /// Converts a schema under a keyword TD doesn't define, keeping booleans.
    fn extension_schema(
        &self,
        schema: &Value,
        depth: usize,
        path: &str,
    ) -> Result<Value, ConversionError> {
        match schema {
            Value::Bool(_) => Ok(schema.clone()),
            _ => self.data_schema(schema, depth, path).map(Value::Object),
        }
    }

    fn resolve(&self, reference: &Value, path: &str) -> Result<&Value, ConversionError> {
        let reference = reference
            .as_str()
            .ok_or_else(|| ConversionError::NotASchema {
                found: reference.to_string(),
                path: format!("{path}/$ref"),
            })?;
        let pointer =
            reference
                .strip_prefix('#')
                .ok_or_else(|| ConversionError::NonLocalReference {
                    reference: reference.to_owned(),
                    path: path.to_owned(),
                })?;
        self.root
            .pointer(pointer)
            .ok_or_else(|| ConversionError::UnresolvedReference {
                reference: reference.to_owned(),
                path: path.to_owned(),
            })
    }

    fn check_depth(&self, depth: usize, path: &str) -> Result<(), ConversionError> {
        if depth > self.limit {
            Err(ConversionError::RecursionLimit {
                limit: self.limit,
                path: abbreviate(path),
            })
        } else {
            Ok(())
        }
    }
}

/// Shortens a deep path to its first and last segments, so that a recursion
/// error stays readable.
fn abbreviate(path: &str) -> String {
    const KEEP: usize = 6;
    let segments: Vec<_> = path.split('/').collect();
    if segments.len() <= 2 * KEEP {
        return path.to_owned();
    }
    format!(
        "{}/…/{}",
        segments[..KEEP].join("/"),
        segments[segments.len() - KEEP..].join("/")
    )
}

/// Turns a schema into an object: `true` is `{}`, `false` is an error.
fn as_schema_object(schema: Value, path: &str) -> Result<Map<String, Value>, ConversionError> {
    match schema {
        Value::Object(map) => Ok(map),
        Value::Bool(true) => Ok(Map::new()),
        Value::Bool(false) => Err(ConversionError::FalseSchema {
            path: path.to_owned(),
        }),
        other => Err(ConversionError::NotASchema {
            found: other.to_string(),
            path: path.to_owned(),
        }),
    }
}

/// `base` with every key of `overrides` set on it. Keys already in `base`
/// keep their position.
fn merge(mut base: Map<String, Value>, overrides: Map<String, Value>) -> Map<String, Value> {
    for (key, value) in overrides {
        base.insert(key, value);
    }
    base
}

/// Replaces a `type` array with a `oneOf` of single-type branches.
fn split_type_array(
    obj: &mut Map<String, Value>,
    types: &[Value],
    path: &str,
) -> Result<(), ConversionError> {
    let types = types
        .iter()
        .map(|t| t.as_str().map(str::to_owned))
        .collect::<Option<Vec<_>>>()
        .ok_or_else(|| conflict("`type` must contain only strings", path))?;
    // `number` already includes integers. Keeping both would create
    // overlapping `oneOf` branches and reject integer values.
    let has_number = types.iter().any(|t| t == "number");
    let mut distinct = Vec::with_capacity(types.len());
    for data_type in types {
        if (data_type != "integer" || !has_number) && !distinct.contains(&data_type) {
            distinct.push(data_type);
        }
    }
    let types = distinct;
    match types.as_slice() {
        [] => return Err(conflict("`type` is an empty array", path)),
        [single] => {
            obj.insert("type".to_owned(), single.clone().into());
            return Ok(());
        }
        _ => {}
    }
    if obj.contains_key("oneOf") {
        return Err(conflict(
            "`type` is an array and `oneOf` is also present",
            path,
        ));
    }

    let mut branches: Vec<Map<String, Value>> = types
        .iter()
        .map(|t| {
            let mut branch = Map::new();
            branch.insert("type".to_owned(), t.clone().into());
            for &keyword in type_keywords(t) {
                if let Some(value) = obj.get(keyword) {
                    branch.insert(keyword.to_owned(), value.clone());
                }
            }
            branch
        })
        .collect();
    obj.shift_remove("type");
    for t in &types {
        for &keyword in type_keywords(t) {
            obj.shift_remove(keyword);
        }
    }

    // Each `enum` value goes to the branch of its own type. A branch that
    // gets no values can't match anything, so it is dropped.
    let mut keep = vec![true; branches.len()];
    if let Some(Value::Array(values)) = obj.get("enum").cloned() {
        obj.shift_remove("enum");
        let mut per_branch = vec![Vec::new(); branches.len()];
        for value in values {
            let i = branch_for(&types, &value).ok_or_else(|| {
                conflict(
                    &format!("enum value {value} matches none of the types"),
                    path,
                )
            })?;
            per_branch[i].push(value);
        }
        for (i, values) in per_branch.into_iter().enumerate() {
            if values.is_empty() {
                keep[i] = false;
            } else if types[i] != "null" {
                branches[i].insert("enum".to_owned(), Value::Array(values));
            }
        }
    }
    if let Some(value) = obj.shift_remove("const") {
        let i = branch_for(&types, &value).ok_or_else(|| {
            conflict(
                &format!("const value {value} matches none of the types"),
                path,
            )
        })?;
        keep.iter_mut().enumerate().for_each(|(j, k)| *k &= j == i);
        if types[i] != "null" {
            branches[i].insert("const".to_owned(), value);
        }
    }

    let mut branches: Vec<_> = branches
        .into_iter()
        .zip(keep)
        .filter_map(|(branch, keep)| keep.then_some(branch))
        .collect();
    match branches.len() {
        0 => Err(conflict("no type allows any of the enum values", path)),
        1 => {
            obj.extend(branches.pop().expect("one branch"));
            Ok(())
        }
        _ => {
            obj.insert(
                "oneOf".to_owned(),
                Value::Array(branches.into_iter().map(Value::Object).collect()),
            );
            Ok(())
        }
    }
}

/// The keywords that only apply to values of type `t`.
fn type_keywords(t: &str) -> &'static [&'static str] {
    match t {
        "integer" | "number" => &[
            "minimum",
            "maximum",
            "exclusiveMinimum",
            "exclusiveMaximum",
            "multipleOf",
            "format",
        ],
        "string" => &[
            "minLength",
            "maxLength",
            "pattern",
            "format",
            "contentEncoding",
            "contentMediaType",
            "contentSchema",
        ],
        "array" => &[
            "items",
            "additionalItems",
            "unevaluatedItems",
            "minItems",
            "maxItems",
            "uniqueItems",
            "contains",
            "minContains",
            "maxContains",
        ],
        "object" => &[
            "properties",
            "required",
            "additionalProperties",
            "patternProperties",
            "propertyNames",
            "unevaluatedProperties",
            "minProperties",
            "maxProperties",
            "dependentRequired",
            "dependentSchemas",
        ],
        _ => &[],
    }
}

/// The index of the type in `types` that `value` belongs to. Whole numbers
/// prefer `integer` and fall back to `number`.
fn branch_for(types: &[String], value: &Value) -> Option<usize> {
    let position = |name: &str| types.iter().position(|t| t == name);
    match value {
        Value::Null => position("null"),
        Value::Bool(_) => position("boolean"),
        Value::String(_) => position("string"),
        Value::Array(_) => position("array"),
        Value::Object(_) => position("object"),
        Value::Number(n) => {
            let whole = n.is_i64() || n.is_u64() || n.as_f64().is_some_and(|f| f.fract() == 0.0);
            whole
                .then(|| position("integer"))
                .flatten()
                .or_else(|| position("number"))
        }
    }
}

/// Whether `format` is one of the numeric formats schemars adds, which are
/// not JSON Schema formats.
fn is_numeric_format(format: &str) -> bool {
    matches!(
        format,
        "int"
            | "int8"
            | "int16"
            | "int32"
            | "int64"
            | "int128"
            | "uint"
            | "uint8"
            | "uint16"
            | "uint32"
            | "uint64"
            | "uint128"
            | "float"
            | "double"
    )
}

fn conflict(message: &str, path: &str) -> ConversionError {
    ConversionError::Conflict {
        message: message.to_owned(),
        path: path.to_owned(),
    }
}

/// Escapes a key for a JSON pointer.
fn escape(key: &str) -> String {
    key.replace('~', "~0").replace('/', "~1")
}
